# Generated by Django 3.2.6 on 2021-10-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diabetic', models.CharField(default='Y', max_length=50, verbose_name='diabetic')),
                ('gender', models.CharField(max_length=50, verbose_name='gender')),
                ('age', models.IntegerField(verbose_name='age')),
                ('parents', models.CharField(max_length=50, verbose_name='parents')),
                ('siblings', models.CharField(max_length=50, verbose_name='siblings')),
                ('fast_food_in_night', models.CharField(max_length=50, verbose_name='fast food in night')),
                ('sweet', models.CharField(max_length=50, verbose_name='sweet')),
                ('hypertension', models.CharField(max_length=50, verbose_name='hypertension')),
                ('stress', models.CharField(max_length=50, verbose_name='stress')),
                ('delayed_healing_wounds', models.CharField(max_length=50, verbose_name='delayed healing wounds')),
                ('delayed_bruise_recovery', models.CharField(max_length=50, verbose_name='delayed bruise recovery')),
                ('thirst', models.CharField(max_length=50, verbose_name='thirst')),
                ('urination', models.CharField(max_length=50, verbose_name='urination')),
                ('tired', models.CharField(max_length=50, verbose_name='tired')),
                ('blurred_vision', models.CharField(max_length=50, verbose_name='blurred vision')),
                ('numbness', models.CharField(max_length=50, verbose_name='numbness')),
                ('smoking', models.CharField(max_length=50, verbose_name='smoking')),
                ('sport', models.CharField(max_length=50, verbose_name='sport')),
                ('BMI', models.FloatField(verbose_name='BMI')),
                ('area', models.CharField(max_length=50, verbose_name='area')),
            ],
        ),
    ]
