# Generated by Django 3.2.6 on 2021-09-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='graphs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diabetic', models.CharField(max_length=50, verbose_name='diabetic')),
                ('type', models.CharField(max_length=50, verbose_name='type')),
                ('gender', models.CharField(max_length=50, verbose_name='gender')),
                ('age', models.IntegerField(verbose_name='age')),
                ('parents', models.CharField(max_length=50, verbose_name='parents')),
                ('siblings', models.CharField(max_length=50, verbose_name='siblings')),
                ('meat', models.IntegerField(verbose_name='meat')),
                ('carbohydrates', models.IntegerField(verbose_name='carbohydrates')),
                ('dairy', models.IntegerField(verbose_name='dairy')),
                ('fast_food_in_week', models.IntegerField(verbose_name='fast food in week')),
                ('fast_food_in_night', models.CharField(max_length=50, verbose_name='fast food in night')),
                ('nuts', models.CharField(max_length=50, verbose_name='nuts')),
                ('sweet', models.CharField(max_length=50, verbose_name='sweet')),
                ('sweetened_drinks', models.IntegerField(verbose_name='sweetened drinks')),
                ('hypertension', models.CharField(max_length=50, verbose_name='hypertension')),
                ('surgery', models.CharField(max_length=50, verbose_name='surgery')),
                ('stress', models.CharField(max_length=50, verbose_name='stress')),
                ('delayed_healing_wounds', models.CharField(max_length=50, verbose_name='delayed healing wounds')),
                ('delayed_bruise_recovery', models.CharField(max_length=50, verbose_name='delayed bruise recovery')),
                ('diseases', models.CharField(max_length=50, verbose_name='diseases')),
                ('healthy_food', models.CharField(max_length=50, verbose_name='healthy food')),
                ('thirst', models.CharField(max_length=50, verbose_name='thirst')),
                ('urination', models.CharField(max_length=50, verbose_name='urination')),
                ('infections', models.CharField(max_length=50, verbose_name='infections')),
                ('tired', models.CharField(max_length=50, verbose_name='tired')),
                ('blurred_vision', models.CharField(max_length=50, verbose_name='blurred vision')),
                ('numbness', models.CharField(max_length=50, verbose_name='numbness')),
                ('dark_colored_areas', models.CharField(max_length=50, verbose_name='dark colored areas')),
                ('hunger', models.CharField(max_length=50, verbose_name='hunger')),
                ('chew_food', models.CharField(max_length=50, verbose_name='chew food')),
                ('smoking', models.CharField(max_length=50, verbose_name='smoking')),
                ('stopped_smoking_cigarettes', models.CharField(max_length=50, verbose_name='stopped smoking cigarettes')),
                ('argila', models.CharField(max_length=50, verbose_name='argila')),
                ('sport', models.CharField(max_length=50, verbose_name='sport')),
                ('area', models.CharField(max_length=50, verbose_name='area')),
                ('Urea', models.FloatField(verbose_name='Urea')),
                ('Cr', models.IntegerField(verbose_name='Cr')),
                ('HbA1c', models.FloatField(verbose_name='HbA1c')),
                ('Chol', models.FloatField(verbose_name='Chol')),
                ('TG', models.FloatField(verbose_name='TG')),
                ('HDL', models.FloatField(verbose_name='HDL')),
                ('LDL', models.FloatField(verbose_name='LDL')),
                ('VLDL', models.FloatField(verbose_name='VLDL')),
                ('BMI', models.FloatField(verbose_name='BMI')),
            ],
        ),
        migrations.CreateModel(
            name='survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diabetic', models.CharField(default='Y', max_length=50, verbose_name='diabetic')),
                ('gender', models.CharField(max_length=50, verbose_name='gender')),
                ('age', models.IntegerField(verbose_name='age')),
                ('parents', models.CharField(max_length=50, verbose_name='parents')),
                ('siblings', models.CharField(max_length=50, verbose_name='siblings')),
                ('fast_food_in_night', models.CharField(max_length=50, verbose_name='fast food in night')),
                ('sweet', models.CharField(max_length=50, verbose_name='sweet')),
                ('hypertension', models.CharField(max_length=50, verbose_name='hypertension')),
                ('stress', models.CharField(max_length=50, verbose_name='stress')),
                ('delayed_healing_wounds', models.CharField(max_length=50, verbose_name='delayed healing wounds')),
                ('delayed_bruise_recovery', models.CharField(max_length=50, verbose_name='delayed bruise recovery')),
                ('thirst', models.CharField(max_length=50, verbose_name='thirst')),
                ('urination', models.CharField(max_length=50, verbose_name='urination')),
                ('tired', models.CharField(max_length=50, verbose_name='tired')),
                ('blurred_vision', models.CharField(max_length=50, verbose_name='blurred vision')),
                ('numbness', models.CharField(max_length=50, verbose_name='numbness')),
                ('smoking', models.CharField(max_length=50, verbose_name='smoking')),
                ('sport', models.CharField(max_length=50, verbose_name='sport')),
                ('BMI', models.FloatField(verbose_name='BMI')),
            ],
        ),
    ]
